title:              Mitt Brantevik
email:              info@bl-mc.se
#description:        Accelerating the commercialization of compact particle accelerators with the Blinky-Lite control platform
author:             BL-MC AB
baseurl:            ""
url:                "https://mittbrantevik.se"
numPics:            50

# Social Profiles
twitter_username:   
#github_username:    Blinky-Lite
facebook_username:  
instagram_username:  
linkedin_username:  bl-mc

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
exclude:
  - upload.sh
  - runLocal.sh
  - jekyll-theme-clean-blog.gemspec
  - bin
  - README.md
  - LICENSE
  - package-lock.json
  - package.json
